@extends('layouts.main')

@section('content')
    
<div class="container  mx-auto">
    <div class="pt-5 pb-8">
        <h1>Test</h1>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a sem velit. Integer sit amet congue nunc. Maecenas euismod magna orci, a ullamcorper nulla tristique volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi congue nec eros eget euismod. Ut ac lacinia tortor. Sed fringilla ultricies neque sit amet eleifend. Donec eu elementum metus, eu elementum lacus. Duis scelerisque lacus id quam condimentum tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fermentum tempus augue, eu placerat lacus sollicitudin vehicula. Curabitur sed est lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce a turpis nisi.</p>
        <p>Suspendisse quis diam a erat bibendum consequat. Donec consequat est et urna ornare dignissim. Morbi interdum velit quis vehicula condimentum. Vestibulum accumsan dolor id arcu tristique, vel viverra felis aliquet. Donec auctor justo at tempus efficitur. Sed eleifend consequat lectus, vel euismod leo efficitur suscipit. Praesent eget mauris nunc. In elit lorem, convallis sed malesuada et, laoreet ut sem. Cras fermentum nulla et fringilla aliquam. Aliquam hendrerit feugiat porttitor. Etiam sed convallis ipsum. Integer convallis pharetra arcu in tempor. Nullam ipsum sem, bibendum vitae mauris eget, pellentesque euismod ipsum. Donec elementum nibh ac ligula congue, at condimentum enim pellentesque.</p>
        <p>Donec pellentesque sem a egestas aliquam. Proin blandit fringilla volutpat. Nulla semper nunc id posuere ultrices. Nunc faucibus enim vel eleifend egestas. Aliquam id condimentum sapien. Etiam faucibus in justo ultricies accumsan. Nulla quis efficitur purus, non suscipit lectus.</p>
        <p>Nam congue arcu id justo mollis pharetra. Pellentesque turpis nisl, lobortis in massa vitae, consequat suscipit lectus. Aliquam erat volutpat. Fusce blandit leo ex, eget rhoncus dui bibendum vel. Nunc ac luctus mauris, vitae blandit ligula. Nam quis velit ipsum. Sed a egestas dolor, ut dictum quam. Nulla sollicitudin massa consectetur orci maximus vestibulum.</p>
        <p>Suspendisse orci augue, scelerisque sit amet ante et, scelerisque ornare ante. Vestibulum aliquet rutrum felis, id auctor diam finibus sit amet. Etiam sed imperdiet lorem. Aenean eu quam non quam sodales porttitor. Quisque eu augue eu ex pharetra dapibus. Curabitur at urna arcu. Sed id vulputate nulla. Aliquam placerat placerat dictum. Aliquam et ex id massa faucibus rutrum. In non odio id eros consectetur dignissim. Fusce tellus odio, aliquam sit amet porttitor non, consectetur nec augue. Pellentesque placerat consectetur est, consectetur eleifend tellus consequat eu. Suspendisse suscipit quam eget pellentesque interdum. Nunc sagittis malesuada eleifend. Vivamus eget ullamcorper risus.</p>
    </div>
</div>

@endsection